# RNN Prediction

## Imports and Functions

In [1]:
import pandas as pd

import os
import numpy as np
import sys

import numpy as np
import tensorflow as tf
tf.random.set_seed(42)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import StandardScaler
from tensorflow_addons.metrics import RSquare


c:\Users\marti\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_addons\utils\tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(


In [2]:
# Add the folder to the Python path

os.chdir("../")
# change working directory to project's root path
print(os.getcwd())
folder_path = os.path.abspath("functions/") #INPUT_PATH)#'path_to_your_folder')  # Replace with the actual folder path
sys.path.insert(0, folder_path)

from Predictions import (
    PredictionExperiment,
    PredictionModel
)

c:\Users\marti\Desktop\data\hw_extra


In [3]:
region="chile"
metadata_path = f"data/climate_features/{region}/metadata.csv"
metadata = pd.read_csv(metadata_path)
metadata.reset_index(inplace=True, drop=True)
display(metadata)

id                       filename  season   
0    978f49d7   predictor_978f49d7_1.parquet       1  \
1    978f49d7   predictor_978f49d7_2.parquet       2   
2    978f49d7   predictor_978f49d7_3.parquet       3   
3    978f49d7   predictor_978f49d7_4.parquet       4   
4    978f49d7   predictor_978f49d7_5.parquet       5   
..        ...                            ...     ...   
247  458d357c   predictor_458d357c_8.parquet       8   
248  458d357c   predictor_458d357c_9.parquet       9   
249  458d357c  predictor_458d357c_10.parquet      10   
250  458d357c  predictor_458d357c_11.parquet      11   
251  458d357c  predictor_458d357c_12.parquet      12   

                                               indices  
0    fde0e327-340e2882-43701738-e306f58b-e601b072-e...  
1    fde0e327-340e2882-43701738-e306f58b-e601b072-e...  
2    fde0e327-340e2882-43701738-e306f58b-e601b072-e...  
3    fde0e327-340e2882-43701738-e306f58b-e601b072-e...  
4    fde0e327-340e2882-43701738-e306f58b-e601b072-e...  
..                                                 ...  
247  32f131d2-69ffcfa8-4af95abb-4a86cb22-52eda853-3...  
248  32f131d2-69ffcfa8-4af95abb-4a86cb22-52eda853-3...  
249  32f131d2-69ffcfa8-4af95abb-4a86cb22-52eda853-3...  
250  32f131d2-69ffcfa8-4af95abb-4a86cb22-52eda853-3...  
251  32f131d2-69ffcfa8-4af95abb-4a86cb22-52eda853-3...  

[252 rows x 4 columns]

In [4]:
data = {i: pd.read_parquet(f"data/climate_features/{region}/predictor_9bd58418_{i}.parquet") for i in range(1,13)}
data[12]

fde0e327-sst  340e2882-sst  b91ccd4e-t  c6184040-max_value   
0       1.919132      1.738772    1.089508           97.656250  \
1      -1.787336     -1.410034   -0.630829          373.351562   
2      -0.924454     -1.843321   -0.622803          176.867188   
3      -1.654869     -1.510971   -0.594147          257.140625   
4      -1.731778     -0.329125   -0.561279         -177.140625   
5       0.333758      1.009113    1.376251          479.250000   
6       0.319313      0.542892    1.694794          389.710938   
7       0.408862      0.216794    0.038391            1.476562   
8      -0.305299     -0.773594    0.053955            8.046875   
9      -1.057992     -0.154225   -0.037231          511.515625   
10      2.787631      3.281134    1.904541           78.195312   
11     -0.941696      0.118529    2.358032          145.171875   
12     -0.891779      0.668478   -0.367432          240.671875   
13     -0.822953     -0.111657    0.459320          509.304688   
14     -0.477985      0.791476    1.455139          326.085938   
15      1.114140      0.559251   -0.345276          214.601562   
16      0.800834      0.567632   -0.110260          181.664062   
17     -2.025564     -0.756622   -0.845428          168.304688   
18      0.122514      0.031417   -0.428619          286.773438   
19      0.577545      0.038116   -2.803192          109.968750   
20      1.917992      0.805571   -1.676941          112.273438   
21      0.305154     -0.564701   -0.055542          167.328125   
22      1.290145      0.759400    0.301636          121.617188   
23     -0.994559     -0.997697    3.390656          267.171875   
24     -0.622711     -1.414225   -0.558289          482.539062   
25      2.904834      4.005782   -0.664856          467.734375   
26     -1.883779     -0.649003    1.052490          309.171875   
27     -1.764071     -1.088994   -0.132904          471.460938   
28     -0.813097     -1.028325   -0.153351          187.953125   
29     -0.316208     -1.001537    2.926208          253.609375   
30      1.545902      0.684458   -0.716248           73.984375   
31      0.407281      0.095528   -2.356140          522.773438   
32      0.804391     -0.036971   -0.764587           98.296875   
33     -0.623110     -0.775934    0.359375          635.664062   
34      1.271118      0.596909   -1.518921          279.187500   
35     -1.503137     -2.069502    0.145416          356.726562   
36     -0.815855     -0.599653    1.963348          576.476562   
37      1.694864      0.298523   -1.240906          425.710938   
38     -1.684551     -1.279567   -1.594513          741.007812   
39     -0.972525     -0.811385    2.480347          340.070312   
40     -0.060150     -0.674154   -2.604309          196.914062   
41      0.038625     -0.281197    1.889008          293.242188   
42      0.798505     -0.066134   -0.601898          394.335938   
43      2.696853      1.828449   -0.069305          241.273438   
44     -0.289804     -0.283383    0.296448           69.273438   
45     -0.805386     -1.339101    1.041809          173.921875   
46      0.888151      0.463281    0.174347          416.359375   
47      0.498531      0.105024    0.890228          193.250000   
48     -1.032100     -0.932777    0.294556          236.789062   
49     -0.892110     -1.568828    2.215240          571.453125   
50     -0.777572     -0.755047    1.604645          218.343750   

    c6184040-latitude  c6184040-longitude  c1c59e4d-u  8c4a4c9c-u  cb76aaa7-u   
0              -44.75              284.00    0.105871   -0.078898   -0.430445  \
1              -30.50              254.75   -0.627693   -0.089662   -0.409054   
2              -45.00              267.00   -0.043367   -0.130367   -1.143116   
3              -39.75              245.00   -0.916506   -0.131766    0.242939   
4              -15.00              283.75   -0.382942    0.059941    1.272537   
5              -45.00              279.75   -1.298745   -0.230251   -1.866019   
6   

In [5]:
indices_of_interest = ["HWN", "HWF", "HWD", "HWA", "HWM"]
label = ["HWF","HWD"]
#data[12].drop(columns=indices_of_interest, inplace=True)
features = data[12].columns.difference(indices_of_interest)

X = data[12][features]
y = data[12][indices_of_interest]
n_labels = len(indices_of_interest)

n_samples = X.shape[0]
n_features = len(features)
model = PredictionModel(data[12], 12, indices_of_interest, Sequential([
    SimpleRNN(16, activation="tanh", input_shape=(1, n_features)),
    Dropout(0.1),  # Regularization
    Dense(8, activation="relu"),
    Dense(n_labels)  # Predict 5 indices
]), name_regressor="RNN")

In [6]:
model.train_predict(5) ##check how to mesaure metrics correctly because of NN using 5 size output layer

1/1 [==============================] - 0s 14ms/step
[0.09803922 0.10021786 0.10021786 0.10021786 0.10021786 0.10021786
 0.10021786 0.10021786 0.10021786 0.10021786]
2/2 [==============================] - 0s 2ms/step


In [12]:
model.get_metric("mae", "CV")

['RNN',
 12,
 'mae',
 'CV',
 0.5374250984345013,
 0.4159048424597797,
 0.4315235333695399,
 0.5283999179911831,
 0.483200864679509,
 0.47929085138690264]

In [5]:
indices_of_interest = ["HWN", "HWF", "HWD", "HWA", "HWM"]
label = ["HWF","HWD"]
#data[12].drop(columns=indices_of_interest, inplace=True)
features = data[12].columns.difference(indices_of_interest)

X = data[12][features]
y = data[12][indices_of_interest]
n_labels = len(indices_of_interest)

n_samples = X.shape[0]
n_features = len(features)

# Standardize inputs
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_scaled = scaler_X.fit_transform(X)
y_scaled = scaler_y.fit_transform(y)

# Reshape for RNN/LSTM (samples, timesteps=1, features)
X_scaled = X_scaled.reshape((n_samples, 1, n_features))  

# Train/Validation split
X_train, X_val = X_scaled[:46], X_scaled[46:]
y_train, y_val = y_scaled[:46], y_scaled[46:]


In [14]:
# Define an RNN model with Dropout
rnn_model = Sequential([
    SimpleRNN(16, activation="tanh", input_shape=(1, n_features)),
    Dropout(0.1),  # Regularization
    Dense(8, activation="relu"),
    Dense(n_labels)  # Predict 5 indices
])

# Compile
rnn_model.compile(optimizer="adam", loss="mae", metrics=["mse", "mape", RSquare()])

# Early stopping callback
early_stopping = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)

# Train with validation
rnn_model.fit(X_train, y_train, epochs=200, batch_size=8, validation_data=(X_val, y_val),
              callbacks=[early_stopping], verbose=1)

# Summary
rnn_model.summary()


Epoch 1/200
6/6 [==============================] - 3s 79ms/step - loss: 0.8858 - mse: 1.2780 - mape: 247.9996 - r_square: -0.4531 - val_loss: 1.1801 - val_mse: 2.1849 - val_mape: 114.1782 - val_r_square: -0.6159
Epoch 2/200
6/6 [==============================] - 0s 12ms/step - loss: 0.8165 - mse: 1.1508 - mape: 211.7742 - r_square: -0.3085 - val_loss: 1.1671 - val_mse: 2.1323 - val_mape: 111.8369 - val_r_square: -0.5853
Epoch 3/200
6/6 [==============================] - 0s 12ms/step - loss: 0.8207 - mse: 1.1745 - mape: 217.6633 - r_square: -0.3386 - val_loss: 1.1553 - val_mse: 2.0857 - val_mape: 109.4768 - val_r_square: -0.5601
Epoch 4/200
6/6 [==============================] - 0s 12ms/step - loss: 0.7639 - mse: 1.0600 - mape: 187.5799 - r_square: -0.2058 - val_loss: 1.1467 - val_mse: 2.0502 - val_mape: 107.4829 - val_r_square: -0.5408
Epoch 5/200
6/6 [==============================] - 0s 12ms/step - loss: 0.7585 - mse: 1.0268 - mape: 202.1478 - r_square: -0.1629 - val_loss: 1.1404 - v

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score, mean_absolute_percentage_error
from sklearn.model_selection import train_test_split, cross_val_score, TimeSeriesSplit
rnn_model = Sequential([
    SimpleRNN(16, activation="tanh", input_shape=(1, n_features)),
    Dropout(0.1),  # Regularization
    Dense(8, activation="relu"),
    Dense(n_labels)  # Predict 5 indices
])
def reshape_for_keras(X):
    return np.expand_dims(X, axis=1)
tscv = TimeSeriesSplit(test_size=5)
X = data[12][features]
y = data[12][indices_of_interest]
r2_tscv = []
mape_tscv= []
train_sizes = []
for train_index, test_index in tscv.split(X):
    train_sizes.append(len(train_index))
    train_data, test_data, y_train, y_test = X.iloc[train_index], X.iloc[test_index], y.iloc[train_index], y.iloc[test_index]
    X_train = reshape_for_keras(train_data)
    X_test = reshape_for_keras(test_data)
    rnn_model.compile(optimizer="adam", loss="mae")
    rnn_model.fit(X_train, y_train, epochs=200, batch_size=8, verbose=0, validation_data=(X_test, y_test))
    pred = rnn_model.predict(X_test)
    r2_tscv.append(r2_score(y_test, pred, multioutput="raw_values")) 
    mape_tscv.append(mean_absolute_percentage_error(y_test, pred, multioutput="raw_values"))
weights = np.array(train_sizes)/np.sum(train_sizes)
r2_tscv = np.dot(np.array(r2_tscv).T,weights)
mape_tscv = np.dot(np.array(mape_tscv).T,weights)

1/1 [==============================] - 0s 92ms/step
[array([0.70361004, 0.68047515, 0.72400961, 0.64392887, 0.63689179]), array([ -1.05026093,  -4.60477475,  -1.20002839, -15.7154569 ,
       -14.37387745]), array([0.71218407, 0.92948281, 0.88717301, 0.8204686 , 0.84586961]), array([0.66614026, 0.43188497, 0.45762006, 0.32655183, 0.52341476]), array([ 0.32980692,  0.3549644 ,  0.25480821, -0.40912829, -0.52822707])]


In [15]:
r2_tscv = np.dot(r2_tscv, weights)
r2_tscv

array([ 0.29920704, -0.3197702 ,  0.24469555, -2.479619  , -2.23010082])

In [15]:
# Define an LSTM model with Dropout
lstm_model = Sequential([
    LSTM(16, activation="tanh", input_shape=(1, n_features)),
    Dropout(0.1),  # Regularization
    Dense(8, activation="relu"),
    Dense(n_labels)  # Predict 5 indices
])

# Compile
lstm_model.compile(optimizer="adam", loss="mae", metrics=["mse", "mape", RSquare()])

# Train with validation
lstm_model.fit(X_train, y_train, epochs=200, batch_size=8, validation_data=(X_val, y_val),
               callbacks=[early_stopping], verbose=1)

# Summary
lstm_model.summary()


Epoch 1/200
6/6 [==============================] - 3s 100ms/step - loss: 0.7473 - mse: 0.9057 - mape: 146.3605 - r_square: -0.0233 - val_loss: 1.1267 - val_mse: 1.9693 - val_mape: 97.3572 - val_r_square: -0.5427
Epoch 2/200
6/6 [==============================] - 0s 10ms/step - loss: 0.7334 - mse: 0.8930 - mape: 126.6799 - r_square: -0.0089 - val_loss: 1.1252 - val_mse: 1.9685 - val_mape: 96.6118 - val_r_square: -0.5421
Epoch 3/200
6/6 [==============================] - 0s 10ms/step - loss: 0.7214 - mse: 0.8768 - mape: 132.0839 - r_square: 0.0090 - val_loss: 1.1234 - val_mse: 1.9657 - val_mape: 95.9315 - val_r_square: -0.5398
Epoch 4/200
6/6 [==============================] - 0s 10ms/step - loss: 0.7118 - mse: 0.8699 - mape: 124.9203 - r_square: 0.0173 - val_loss: 1.1223 - val_mse: 1.9689 - val_mape: 95.2261 - val_r_square: -0.5422
Epoch 5/200
6/6 [==============================] - 0s 9ms/step - loss: 0.7018 - mse: 0.8511 - mape: 125.4212 - r_square: 0.0391 - val_loss: 1.1221 - val_mse:

In [8]:
lstm_model.get_metrics_result()

{'loss': <tf.Tensor: shape=(), dtype=float32, numpy=2.0460103>,
 'mae': <tf.Tensor: shape=(), dtype=float32, numpy=1.1040316>,
 'mape': <tf.Tensor: shape=(), dtype=float32, numpy=84.136955>,
 'r_square': <tf.Tensor: shape=(), dtype=float32, numpy=-0.59095705>}